### ISSUE TITLE
Date is not displayed pre-select if the selected date is not in current month

### ISSUE THREAD

**Issue by bernard4uece** [kesarion/angular2-air-datepicker#15]
@kesarion I hope this issue can be easily resolved. The issue is when I bind AirDate with any date that is not in current month and opening the calendar doesn't display that particular date pre-selected which it does if the selected date is in current month. However if I navigate to that calendar month, I can see that showing selected.

**Comment by bernard4uece** [comment]
@kesarion would appreciate if you could try to implement the above requested

**Comment by kesarion** [comment]
@bernard4uece I'm not able to reproduce this with the latest version. The date is pre-selected even if the bound date is from another month. If you still have this issue, try to reproduce it in [Stackblitz](https://stackblitz.com/angular/qmdqkqyqdqm) or similar and send me a link so I can see what you're doing.

**Comment by bernard4uece** [comment]
I tried to recreated but that issue is not recreatable but it still persists in my local code. I think I am binding using model class that is initially null. However I did see another issue. Please check my stackblitz and if you select a new date, you may notice the textbox displays selected date minus 1 day. That's odd but not sure what is causing that.
https://stackblitz.com/edit/angular6-air-datepicker-demo?file=app%2Fapp.component.ts

**Comment by bernard4uece** [comment]
@kesarion I just updated stackblitz, when you get chance please take a look

**Comment by kesarion** [comment]
@bernard4uece I appreciate the stackblitz project, this makes things easier.

I think I understand what your first issue is. The thing is, the component date isn't supposed to be set externally more than once. Normally, you set the date once and then the user is responsible for choosing a new date through the calendar. If you start changing the date after the calendar has been rendered, that would be confusing for the user, so it wouldn't make sense in most cases. My recommendation here:
If you need to wait for the date from an external source (e.g. API), don't render the calendar until you have the date, perhaps show a loading animation.
If you must set the date externally, more than once, simply re-render the calendar. I think that would be appropriate in this rather rare case.
If you must have this feature, please make another github issue for it, this one's veered quite a bit from the actual issue, perhaps name it "Re-focus the selected date on external date change". I don't see it as much of a priority, though, unless you have one or more good use cases in mind.

As for the second issue, it seems related to Javascript's auto timezone conversion behaviour; try doing a `console.log(new Date('2018-10-10 00:00:00'));` and see what you get. For example, for me it outputs `Date 2018-10-09T21:00:00.000Z`, because I'm at UTC+03:00 (usually +2, but now with DST). That's what you're sending to the calendar. Interestingly, if you omit the time part, it won't do the conversion and the date will be correct: `console.log(new Date('2018-10-10'));`. If you need the time then you should make sure you're sending the right one. Although, I'm not completely sure about this one, get back to me with your results after using the right dates.

**Comment by bernard4uece** [comment]
@kesarion for the second scenario, if I set just date as 2018-10-10 I have as Tue Oct 09 2018 20:00:00 GMT-0400 (Eastern Daylight Time) but if I set date as 2018-10-10 00:00:00 then it is parsed as Wed Oct 10 2018 00:00:00 GMT-0400 (Eastern Daylight Time)

**Comment by bernard4uece** [comment]
@kesarion I am not sure how I can handle that in my project. Not sure how I can render when the date is valid. For my situation the date may be null or valid but I have to show the calendar. I will have to dive deep to see dynamic rendering of this control can be achieved

**Comment by kesarion** [comment]
> 
> 
> @kesarion for the second scenario, if I set just date as 2018-10-10 I have as Tue Oct 09 2018 20:00:00 GMT-0400 (Eastern Daylight Time) but if I set date as 2018-10-10 00:00:00 then it is parsed as Wed Oct 10 2018 00:00:00 GMT-0400 (Eastern Daylight Time). Either way setting date only is taking previous day or setting zero time is messing up selecting new date. I think it's more of time zone problem the date picker is not able to handle. I am in time zone of GMT - 4.

@bernard4uece All right, forget what I said in my earlier comment, it's the other way around.

The calendar is timezone agnostic, it doesn't know about timezones, the date it receives (after being manipulated by the browser JS) is the date it will use, it doesn't do any conversions at all.

When you do a `new Date(''2018-10-10 00:00:00)`, the browser interprets the date correctly, the calendar should work just fine. I tested this a few moments ago.
When you do a `new Date(''2018-10-10)`, it does a conversion from UTC to local, which is why you're seeing it go -4 hours. As you can expect, the calendar doesn't know which one you're doing, it can't know, so you have to add the timezone offset yourself. One way:

```javascript
let localDate = new Date('2018-10-10');
let desiredDate = new Date(localDate.getTime() + localDate.getTimezoneOffset() * 60000);
```

Or just add `' 00:00:00'` to the string if it's missing ;)

---

As for the other issue, you just need a variable like `showCalendar = false;`, when the date is valid set it to true:

```html
<air-calendar *ngIf="showCalendar"></air-calendar>
```

**Comment by bernard4uece** [comment]
@kesarion thanks so much for your quick response. I think I figured out what the issue and cleaned up the code. Everything works fine now. If you like to include that demo in your read me please feel free and if you like to clean up that is fine too
