### ISSUE TITLE
Simpler error message if  [(airDate)]="date" is missing

### ISSUE THREAD

**Issue by lars159** [kesarion/angular2-air-datepicker#17]
if [(airDate)]="date" is missing as a attribute you get the following error message 

> Cannot read property 'getFullYear' of undefined
Maybe add a simpler error message

**Comment by kesarion** [comment]
Sorry this took so long, I'd been planing an update for the date internals and wanted to handle issues afterwards (due to potential breaking changes and some issues becoming obsolete). That took a much longer time than I expected, though...

Well, this looks like it's obsolete/fixed with v2. The date object can now be null, or basically you don't need to set airDate anymore if you don't need to, and you can simply rely on the airChange event.
