### ISSUE TITLE
how to redraw calendar after enabledDateRanges change

### ISSUE THREAD

**Issue by rozumny** [kesarion/angular2-air-datepicker#27]
Hello, I populate enabledDateRanges and draw a calendar. Then I remove some date from enabledDateRanges and want to redraw the calendar. How can I achieve that?

**Comment by kesarion** [comment]
Sorry this took so long, I'd been planing an update for the date internals and wanted to handle issues afterwards (due to potential breaking changes and some issues becoming obsolete). That took a much longer time than I expected, though...

I'd use an `*ngIf="dateRangeStillValid()"` or something like that to solve this sort of issue.
